'use client';
import React from 'react';
import Modal from '@/components/ui/Modal';
import Button from '@/components/ui/Button';
import { Printer, CheckCircle } from 'lucide-react';

export default function ReceiptModal({ isOpen, onClose, receiptData }) {
  if (!receiptData) return null;

  const handlePrint = () => {
    // Trigger print — globals.css @media print styles handle white bg + single page
    window.print();
  };

  const date = receiptData.date
    ? receiptData.date
    : receiptData.createdAt
    ? new Date(receiptData.createdAt).toLocaleDateString('en-IN', {
        day: '2-digit',
        month: 'long',
        year: 'numeric',
      })
    : new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Official Temple Receipt" maxWidth="max-w-lg">
      {/* Action Buttons — hidden on print via .no-print class */}
      <div className="no-print flex items-center gap-3 mb-5">
        <Button variant="primary" size="md" className="flex-1" onClick={handlePrint} icon={Printer}>
          Print / Save as PDF
        </Button>
        <Button variant="secondary" size="md" onClick={onClose}>
          Close
        </Button>
      </div>

      {/* ===== PRINTABLE RECEIPT AREA ===== */}
      {/* This div is targeted by @media print in globals.css */}
      <div id="printable-receipt">
        {/* Success marker — screen only */}
        <div className="no-print text-center pb-4 border-b border-[#5E645A]/50 mb-4">
          <div className="inline-flex items-center justify-center w-10 h-10 rounded-full bg-[#233728] text-[#4F7A4D] mb-2">
            <CheckCircle className="w-5 h-5" />
          </div>
          <p className="text-xs text-[#4F7A4D]">Receipt Confirmed. May Shree Nagaraja bless you.</p>
        </div>

        {/* ---- RECEIPT CONTENT (renders white on print) ---- */}
        <div className="receipt-content space-y-0">

          {/* Temple Header */}
          <div className="receipt-header text-center pb-4 mb-4" style={{ borderBottom: '2px solid #9B7A41' }}>
            <h2 className="receipt-temple-name" style={{ fontFamily: 'serif', fontSize: '18px', fontWeight: 'bold', margin: '0 0 4px 0' }}>
              Mevakkatu Shree Nagaraja Kshetram
            </h2>
            <p style={{ fontSize: '12px', margin: '0', color: '#555' }}>
              Sacred Serpent Temple Trust • Kerala, India
            </p>
            <p style={{ fontSize: '11px', margin: '4px 0 0 0', color: '#777' }}>
              Official Digital Receipt — {receiptData.receiptId}
            </p>
          </div>

          {/* Receipt Row Helper */}
          {[
            { label: 'Devotee Name', value: receiptData.devoteeName || receiptData.donorName },
            receiptData.star && { label: 'Birth Star (Nakshatra)', value: receiptData.star },
            receiptData.poojaName && { label: 'Offering / Pooja', value: receiptData.poojaName },
            receiptData.purpose && { label: 'Donation Purpose', value: receiptData.purpose },
            { label: 'Date of Offering', value: date },
            { label: 'Transaction ID', value: receiptData.paymentId || receiptData.receiptId || 'TXN-ONLINE-SUCCESS' },
          ]
            .filter(Boolean)
            .map(({ label, value }, idx) => (
              <div
                key={idx}
                style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  padding: '8px 0',
                  borderBottom: '1px solid #e0e0e0',
                  fontSize: '13px',
                }}
              >
                <span style={{ color: '#555', fontWeight: '500' }}>{label}:</span>
                <span style={{ color: '#111', fontWeight: '600', textAlign: 'right', maxWidth: '55%' }}>{value}</span>
              </div>
            ))}

          {/* Total Amount */}
          <div
            style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              padding: '12px 16px',
              marginTop: '12px',
              background: '#f5f0e8',
              borderRadius: '8px',
              border: '1px solid #9B7A41',
            }}
          >
            <span style={{ fontSize: '15px', fontWeight: '600', color: '#333' }}>Total Amount Paid:</span>
            <span style={{ fontSize: '20px', fontWeight: '800', color: '#9B7A41' }}>₹{receiptData.amount}</span>
          </div>

          {/* Footer Note */}
          <p
            style={{
              fontSize: '10px',
              color: '#888',
              textAlign: 'center',
              marginTop: '16px',
              fontStyle: 'italic',
              lineHeight: '1.5',
            }}
          >
            This digital receipt is automatically generated by Mevakkatu Shree Nagaraja Kshetram Trust.
            <br />
            Present at the temple counter if collecting prasadam in person.
          </p>
        </div>
      </div>
    </Modal>
  );
}
